name: Build dinput8

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build Release Win32
        shell: cmd
        run: |
          msbuild dinput8.sln ^
            /m ^
            /p:Configuration=Release ^
            /p:Platform=Win32 ^
            /v:minimal

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: dinput8-win32
          path: |
            **\Release\dinput8.dll
            **\Win32\Release\dinput8.dll
